sudo: required
services:
- docker
language: python
python:
- '2.7'
script:
- docker build -t recast/frontend-rest-server:git-"$TRAVIS_BRANCH" .
- docker login -u $DOCKERLOGIN -p $(echo $DOCKERPW|base64 -d)
- docker push recast/frontend-rest-server:git-"$TRAVIS_BRANCH"
env:
  global:
  - secure: MDAx0jXfLH7lARo4Q77pUCld6R1MyI9jechJDTRssRxfjecDpjFt8e6MXuZsbL3c+fJX26eNZ+N/NoB9xaa7oJNuyAqvMzMnpirPloJ2y1D/Q0dhSpfp97K3ML9S2LBL5aKDAwK1Q1JeNKzIhFi+gi2Ft+Mhj1J79nQlaKxOSwp6A6qDUcMrb/oZhrhMkj647ZlEuCN+J+fGAPJq14++HSNl6oXc/aMZhzr+cXlLo2XpQijzXJRtEMG7KdGo9A5Dv3/IZ9lNG7wOj2GTQVIe3vvuQ7ifmrbAWLw5uKuIVCLaKSFjGsrroJlAE1eUKdh+mx9D5fFyWCPnsVCzganuSUrm8p/gwBwA/FYFJnZ++VQMLo1BwSQjlM8blQrojSn+EHqLZQW5pnQAh103eiDWaewocFfNVRorN+pwbnMcsIuTD19ZchI0xwE7NbVHEhbov7vf/VKk4eak3VvveDANWR07a5WVRj4srMgHK91NcPwR2j6ZJ7jSM8G6gnGgUi1Q/24xblthlE3W8qZxI5sEGzFIpZEuLcUFQ5DRC1DCKXGZ22gfZQtnB5OghRG/PPU6L+/dUR1Q+zeixAha3IjhJovY3MKeeUFQ4WOM3NtvIb23hCxZiYWCpwwAUAIhG4W7ERsp4hlblB3Rzz2uhT0Tblz5ouPYx84s9TK/5Cy9d8A=
  - secure: dkZ8ej5wMCNoFlFPeA3BYaxe3ei4actEgFHwI83DIoQMGaseA6uVUKXKTgUYtSLN5LqhHtPlBbaClvD66warCjTSf5+M7KcWumCPLOCalemYN5cMjncMN211nhsuTY/DU8mhsSbpCU5eZ6IE9vEo762Gh80cgXJSDsHqLV3SB95VGp9Xe0oyCWBdYPP5oTvQ74QeiapmBLIQUNEjB0DVvg1Ih9nuG2ALjy175tyocOmVmOB9I+X3xZMw8vgBSKjRuXNvmOq3/jtyQr/SgjFyuEbxyzdkjxx7QoCvRj2pmDCX56kEkDXjcgM+F7MrY6vOrNPPdFq8q5PTr0tqv3qL+BWAjwjD+9kx4EMC8TxAt6M/1Olh5jz9mmlLAlTb3wD7sTkgZIZuFL9zZNU7UwT4SdBI9gcO/yTIlTbFSScBIf2fY5w3UDxkjJUSW7V4mP2MOpi5496VNztdv8uSMGThrxql6t9LzsJ4qefddKpMXH0vcTstZzvG9MFip1R9OE7z1ngmtd6TUq2JRznliD1IXlUd+FLRKY37rApIXsw4vwex1YX/1kGe7GMFoFNB+V2zzxNrYdO6JGtdhqYaZ3ABj1Gqek8dBw5KtjYPyYXFg5xd6mtYiUrIHCoXqH0jhnwckV33SQocoEs57h0NPHlh7Mnm3dKfGZ18qCDTR2WyPvY=
